// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "../node_modules/rescript-test/src/Test.mjs";
import * as Utils from "../src/Utils.mjs";
import * as Js_dict from "../node_modules/rescript/lib/es6/js_dict.js";

var styles = Js_dict.fromArray([[
        "default",
        Js_dict.fromArray([
              [
                "testSmth",
                "testSmthCls"
              ],
              [
                "test-1",
                "test-1-cls"
              ]
            ])
      ]]);

function checkCls(message, name, expected) {
  return Test.assertion(message, "getCls", (function (a, b) {
                return a === b;
              }), Utils.getCls(styles, name), expected);
}

Test.test("#Utils.getCls", (function (param) {
        return checkCls("non existing keys return empty strings", "non-existing-key", "");
      }));

Test.test("#Utils.getCls", (function (param) {
        return checkCls("camel-cased strings are processed correctly", "testSmth", "testSmthCls");
      }));

Test.test("#Utils.getCls", (function (param) {
        return checkCls("kebab-cased strings are processed correctly", "test-1", "test-1-cls");
      }));

export {
  styles ,
  checkCls ,
  
}
/* styles Not a pure module */
