// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Board from "./Board.mjs";
import * as React from "react";

import './reset.css'
;

import './styles.css'
;

function App(Props) {
  return React.createElement("div", undefined, React.createElement(Board.make, {}));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
