// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Board from "./Board.mjs";
import * as Utils from "./Utils.mjs";
import * as React from "react";
import * as Header from "./Header.mjs";
import * as Recoil from "recoil";
import * as GameIntro from "./GameIntro.mjs";
import * as AppModuleCss from "./App.module.css";

import './reset.css'
;

import './styles.css'
;

var styles = AppModuleCss;

function getClassName(param) {
  return Utils.getCls(styles, param);
}

function App(Props) {
  return React.createElement(Recoil.RecoilRoot, {
              children: React.createElement("div", {
                    className: Utils.getCls(styles, "root")
                  }, React.createElement(Header.make, {}), React.createElement(GameIntro.make, {}), React.createElement(Board.make, {}))
            });
}

var make = App;

export {
  styles ,
  getClassName ,
  make ,
  
}
/*  Not a pure module */
