// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AppModuleCss from "./App.module.css";

import './reset.css'
;

var styles = AppModuleCss;

var element = React.createElement("div", undefined, "Hello World");

var heading = React.createElement("h1", undefined, "Overview 123");

function App(Props) {
  return React.createElement("div", {
              className: styles.root
            }, heading, element);
}

var make = App;

export {
  styles ,
  element ,
  heading ,
  make ,
  
}
/*  Not a pure module */
