// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";
import * as BoardModuleCss from "./Board.module.css";

var styles = BoardModuleCss;

var indexes = Belt_Array.makeBy(4, (function (idx) {
        return idx;
      }));

function viewList(render) {
  return Belt_Array.map(indexes, render);
}

function viewCell(rowId, cellId) {
  return React.createElement("div", {
              key: "" + rowId + "-" + cellId + "-cell",
              className: styles.gridCell
            });
}

function viewRow(rowId) {
  return React.createElement("div", {
              key: "" + rowId + "-row",
              className: styles.gridRow
            }, Belt_Array.map(indexes, (function (param) {
                    return viewCell(rowId, param);
                  })));
}

function Board(Props) {
  return React.createElement("div", {
              className: styles.root
            }, React.createElement("div", {
                  className: styles["grid-container"]
                }, Belt_Array.map(indexes, viewRow)));
}

var gridSize = 4;

var make = Board;

export {
  styles ,
  gridSize ,
  indexes ,
  viewList ,
  viewCell ,
  viewRow ,
  make ,
  
}
/* styles Not a pure module */
