// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "../node_modules/rescript/lib/es6/js_dict.js";
import * as Belt_List from "../node_modules/rescript/lib/es6/belt_List.js";
import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "../node_modules/rescript/lib/es6/belt_Option.js";
import * as BoardModuleCss from "./Board.module.css";

var styles = BoardModuleCss;

var indexes = Belt_Array.makeBy(4, (function (idx) {
        return idx;
      }));

var fstTile = {
  val: 2,
  pos: {
    x: 2,
    y: 2
  }
};

var tiles = {
  hd: fstTile,
  tl: /* [] */0
};

function getClassName(name) {
  return Belt_Option.getWithDefault(Belt_Option.flatMap(Js_dict.get(styles, "default"), (function (defaults) {
                    return Js_dict.get(defaults, name);
                  })), "");
}

var viewList = Belt_Array.map;

function viewGridSizedList(param) {
  return Belt_Array.map(indexes, param);
}

function viewCell(rowId, cellId) {
  return React.createElement("div", {
              key: "" + rowId + "-" + cellId + "-cell",
              className: getClassName("gridCell")
            });
}

function viewRow(rowId) {
  return React.createElement("div", {
              key: "" + rowId + "-row",
              className: getClassName("gridRow")
            }, Belt_Array.map(indexes, (function (param) {
                    return viewCell(rowId, param);
                  })));
}

function viewTile(param) {
  var pos = param.pos;
  var val = param.val;
  var valName = "tile-" + val;
  var y = pos.y;
  var x = pos.x;
  var posName = "tilePosition-" + (x + 1 | 0).toString() + "-" + (y + 1 | 0).toString();
  return React.createElement("div", {
              key: "" + val + "-" + x + "-" + y + "-tile",
              className: getClassName("tile") + " " + getClassName(valName) + " " + getClassName(posName)
            }, React.createElement("div", {
                  className: getClassName("tileInner")
                }, val.toString()));
}

function Board(Props) {
  return React.createElement("div", {
              className: getClassName("root")
            }, React.createElement("div", {
                  className: getClassName("gridContainer")
                }, Belt_Array.map(indexes, viewRow)), React.createElement("div", {
                  className: getClassName("tileContainer")
                }, Belt_Array.map(Belt_List.toArray(tiles), viewTile)));
}

var gridSize = 4;

var make = Board;

export {
  styles ,
  gridSize ,
  indexes ,
  fstTile ,
  tiles ,
  getClassName ,
  viewList ,
  viewGridSizedList ,
  viewCell ,
  viewRow ,
  viewTile ,
  make ,
  
}
/* styles Not a pure module */
