// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Rx_Subject = require("@ambientlight/bs-rx/src/internal/Rx_Subject.bs.js");
var UI$FeedbackLoop = require("./UI.bs.js");

console.log("Controller is loaded");

var arg = Curry._1(Rx_Subject.subscribe, (function (x) {
        console.log(x);
        return /* () */0;
      }));

var subscription = (function (eta) {
      return Curry._3(arg, undefined, undefined, eta);
    })(UI$FeedbackLoop.UI.keyDownStream);

exports.subscription = subscription;
/*  Not a pure module */
