// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.mjs";
import * as React from "react";
import * as Scores from "./Scores.mjs";
import * as HeaderModuleCss from "./Header.module.css";

var styles = HeaderModuleCss;

function getClassName(param) {
  return Utils.getCls(styles, param);
}

function Header(Props) {
  return React.createElement("div", {
              className: Utils.getCls(styles, "root")
            }, React.createElement("h1", {
                  className: Utils.getCls(styles, "title")
                }, "2048"), React.createElement(Scores.make, {}));
}

var make = Header;

export {
  styles ,
  getClassName ,
  make ,
  
}
/* styles Not a pure module */
