// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var onDOMContentLoaded = (function(handler) {
            document.addEventListener('DOMContentLoaded', handler, false);
        });

function getUIMessage(text) {
  return /* :: */[
          text,
          /* [] */0
        ];
}

var updateUI = (function(update) {
            document.querySelector('#app').innerHTML = update;
        });

exports.onDOMContentLoaded = onDOMContentLoaded;
exports.getUIMessage = getUIMessage;
exports.updateUI = updateUI;
/* No side effect */
