// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "./State.mjs";
import * as Utils from "./Utils.mjs";
import * as React from "react";
import * as Recoil from "recoil";
import * as ScoresModuleCss from "./Scores.module.css";

var styles = ScoresModuleCss;

function getClassName(param) {
  return Utils.getCls(styles, param);
}

function prepareCounter(x) {
  return String(x);
}

function Scores(Props) {
  var score = Recoil.useRecoilValue(State.scoreState);
  var best = Recoil.useRecoilValue(State.bestScoreState);
  console.log("scores", score);
  return React.createElement("div", {
              className: Utils.getCls(styles, "root")
            }, React.createElement("div", {
                  className: Utils.getCls(styles, "score")
                }, String(score)), React.createElement("div", {
                  className: Utils.getCls(styles, "best")
                }, String(best)));
}

var make = Scores;

export {
  styles ,
  getClassName ,
  prepareCounter ,
  make ,
  
}
/* styles Not a pure module */
