// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.mjs";
import * as Recoil from "recoil";

var fst = Utils.createNewTile(/* [] */0);

var snd = Utils.createNewTile({
      hd: fst,
      tl: /* [] */0
    });

var tilesState = Recoil.atom({
      key: "tilesState",
      default: {
        hd: fst,
        tl: {
          hd: snd,
          tl: /* [] */0
        }
      }
    });

export {
  tilesState ,
  
}
/* tilesState Not a pure module */
