// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.mjs";
import * as Recoil from "recoil";

var tilesState = Recoil.atom({
      key: "tilesState",
      default: {
        hd: Utils.createNewTile(/* [] */0),
        tl: /* [] */0
      }
    });

export {
  tilesState ,
  
}
/* tilesState Not a pure module */
