// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var element = React.createElement("div", undefined, "Hello World");

var heading = React.createElement("h1", undefined, "Overview");

function Test(Props) {
  return React.createElement("div", undefined, heading, element);
}

var make = Test;

export {
  element ,
  heading ,
  make ,
  
}
/* element Not a pure module */
